---

#
# TEAR DOWN, UPDATE, BRING UP
#

- hosts: all
  become_user: root
  become: true
  roles:
    - common
  vars_files:
    - ./site/via_{{customerCode}}.yml
  vars:
    remoteUser: "{{ansible_user}}"
    stoneName: "{{via.siteName}}"
  environment:
    GS_HOME: /opt/GsDevKit_home
    PATH: /opt/GsDevKit_home/bin:{{ ansible_env.PATH }}

  tasks:
  
  # TODO
  # - name: Install maintenance screen
  # - name: Do backup of data

  - include_tasks: tasks_git_update.yml    

  - name: Create Smalltalk updater script
    template:
      src: files/install/updateVia.st.j2
      dest: "{{via.installationPath}}/install/updateVia.st"
      owner: '{{remoteUser}}'
      group: '{{remoteUser}}'
      mode: "u=rwx,g=rwx,o=rx"

    
  - include_tasks: tasks_common.yml

  - name: Stopping VIA's web instances (gems)
    shell: monit -g via_gemstone_gems stop

  - name: Ensure GemStone stone is running
    shell: monit start via_gemstone_stone

  - name: Ensure GemStone netldi is running
    shell: monit start via_gemstone_netldi
      
  # - name: Do backup
  #   become_user: "{{remoteUser}}"
  #   shell: "./backup-image-snapshot.sh"
  #   args:
  #     chdir: "{{via.installationPath}}/server"

  #  - name: certbot renew


  - name: Flush Monticello cache
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} mr flush"

    # mc revert Via ???

  #
  # UPDATE TO NEWEST CODE IN VIA BASE
  # (Very strange, that we have to do that, since I thought Monticell would update subprojects as well?)
  #
  - name: git-clone VIA base project
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} project clone --https --local --checkout=master Via"
    args:
      chdir: "/opt/GsDevKit_home"
      creates: "/opt/GsDevKit_home/shared/repos/via"
      
  - name: Update VIA base project (pull)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} project pull Via"

  - name: Update VIA base project (get)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} project get Via"

  # Hack, GemStone weigert sich irgendwie zu updaten
  - name: Monticello revert to last version (strange, why?)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} mc revert Via"

  
  # - name: Load VIA site project
  #   become_user: "{{remoteUser}}"
  #   command:
  #     argv:
  #       - todeIt
  #       - "{{stoneName}}"
  #       - project
  #       - load
  #       - --loads="\`#('default')\`"
  #       - "{{via.siteName}}"




  #
  # UPDATE TO NEWEST CODE
  #
  - name: Update VIA site project information (pull)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} project pull {{via.siteName}}"

  - name: Update VIA site project information (get)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} project get {{via.siteName}}"
  
  - name: Load VIA site project
    become_user: "{{remoteUser}}"
    command:
      argv:
        - todeIt
        - "{{stoneName}}"
        - project
        - load
        - --loads="\`#('default')\`"
        - "{{via.siteName}}"

  # Hack, GemStone weigert sich irgendwie zu updaten
  - name: Monticello revert to last version (strange, why?)
    become_user: "{{remoteUser}}"
    shell: "todeIt {{stoneName}} mc revert ViaSiteHep"

      
  - name: Update script inside VIA application
    become_user: "{{remoteUser}}"
    shell: "{{via.installationPath}}/via_base/server/executeSmalltalkScript.sh {{stoneName}} {{via.installationPath}}/install/updateVia.st"

  - name: Starting VIA's web instances (gems)
    shell: monit -g via_gemstone_gems start

# TODO
#  - name: Remove maintenance screen

  - include_tasks: tasks_common_end.yml
